name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
        run: |
           run: |
            npm install
            npm run lint:js
            REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY \
            REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN \
            REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID \
            REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET \
            REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID \
            REACT_APP_FIREBASE_APP_ID=$FIREBASE_APP_ID \
            REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL \
            npm run build
          env:
            FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
            FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
            FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
            FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
            FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
            FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
            FIREBASE_DATABASE_URL: ${{ secrets.REACT_APP_FIREBASE_DATABASE_URL }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build